name = "tgchatbot"
main = "worker.js"
compatibility_date = "2025-02-19"

[vars]
# ENV_BOT_TOKEN = 
# ENV_BOT_SECRET = 
# ENV_ADMIN_UID = 

kv_namespaces = [
  { binding = "tgchatbot", id = "YOUR_KV_ID_1" },
]
